/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:be65d3d9-5d77-4c5a-9d69-5e8f8444b5ca",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_tXUZCzWi3",
    "aws_user_pools_web_client_id": "1ir8co4h4auveempnoub746ijg",
    "oauth": {}
};


export default awsmobile;
